"""initial schema

Revision ID: a1f12f2d6b40
Revises: 
Create Date: 2026-02-26 09:41:56.833465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f12f2d6b40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_views_token'), 'guest_views', ['token'], unique=True)
    op.create_index(op.f('ix_guest_views_user_id'), 'guest_views', ['user_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_user_id'), 'properties', ['user_id'], unique=False)
    op.create_table('status_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('invoice_name', sa.String(length=200), nullable=True),
    sa.Column('invoice_address', sa.String(length=500), nullable=True),
    sa.Column('invoice_zip', sa.String(length=20), nullable=True),
    sa.Column('invoice_city', sa.String(length=100), nullable=True),
    sa.Column('invoice_country', sa.String(length=100), nullable=True),
    sa.Column('invoice_vat_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('status_checks')
    op.drop_index(op.f('ix_properties_user_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_guest_views_user_id'), table_name='guest_views')
    op.drop_index(op.f('ix_guest_views_token'), table_name='guest_views')
    op.drop_table('guest_views')
    # ### end Alembic commands ###
